import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// ---------------------------------------------------------------------------
// Translations (bundled in-app — no API call needed to switch language)
// ---------------------------------------------------------------------------
export const TRANSLATIONS = {
  en: {
    // ── Profile screen ──
    myProfile: 'My Profile',
    manageAccount: 'Manage your account & preferences',
    savedAddresses: 'Saved Addresses',
    paymentMethods: 'Payment Methods',
    language: 'Language',
    theme: 'Theme',
    helpSupport: 'Help & Support',
    termsConditions: 'Terms & Conditions',
    logOut: 'Log out',
    logOutConfirmTitle: 'Log out',
    logOutConfirmMsg: 'Are you sure you want to log out?',
    cancel: 'Cancel',
    selectLanguage: 'Select Language',
    done: 'Done',
    switchToDarkTheme: 'Switch to Dark theme',
    switchToLightTheme: 'Switch to Light theme',
    version: 'Vahan360 v1.0.0',
    // ── Home screen ──
    welcomeBack: 'Welcome Back 👋',
    hi: 'Hi',
    locationLabel: 'Koramangala, Bengaluru',
    heroLine1: 'Book rides & deliveries',
    heroLine2: 'in seconds ⚡',
    trustFast: 'Fast',
    trustSafe: 'Safe',
    trustRated: '4.9 Rated',
    searchHint: 'Where to go or send?',
    categoryRide: 'Ride',
    categoryLogistics: 'Logistics',
    categoryTruck: 'Truck',
    categoryPackersMovers: 'Packers & Movers',
    categoryParcel: 'Parcel',
    // ── Packers & Movers screen ──
    packersMoversTitle: 'Packers & Movers',
    packersMoversSubtitle: 'Select your shifting service',
    shiftingMiniTruck: 'Mini Truck',
    shiftingMiniTruckDesc: 'Within city',
    shiftingWithinCity: 'Within City',
    shiftingWithinCityDesc: 'Local home & office shifting',
    shiftingBetweenCities: 'Between Cities',
    shiftingBetweenCitiesDesc: 'Intercity relocation',
    // ── Truck screen ──
    truckTitle: 'Truck',
    truckSubtitle: 'Choose your service',
    truckWithinCity: 'Within City',
    truckWithinCityDesc: 'Local goods transport',
    truckInterCities: 'Inter Cities',
    truckInterCitiesDesc: 'City to city transport',
    truckLongTrips: 'Long Trips',
    truckLongTripsDesc: 'Long distance transport',
    // ── Parcel screen ──
    parcelTitle: 'Parcel',
    parcelSubtitle: 'Choose your delivery type',
    parcelSameCity: 'Same City',
    parcelSameCityDesc: 'Deliver a parcel within the city today',
    parcelInterCity: 'Inter City',
    parcelInterCityDesc: 'Send parcels to another city',
    parcelExpress: 'Express Delivery',
    parcelExpressDesc: 'Priority same-day delivery',
    parcelFastDelivery: '📦 Fast delivery',
    parcelLiveTracking: '📍 Live tracking',
    parcelSafeInsured: '🔒 Safe & insured',
    comingSoon: 'Coming Soon',
    // ── Vehicle screen ──
    chooseVehicle: 'Choose Vehicle',
    confirmVehicle: 'Confirm Vehicle',
    // ── Tab bar ──
    tabHome: 'Home',
    tabOrders: 'Orders',
    tabWallet: 'Wallet',
    tabProfile: 'Profile',
    // ── Notifications screen ──
    notifications: 'Notifications',
    unreadCount: 'unread',
    allCaughtUp: 'All caught up!',
    markAllRead: 'Mark all read',
    // ── Wallet screen ──
    vahanPay: 'Vahan Pay',
    walletSubtitle: 'Fast & secure wallet payments',
    walletBalance: 'Balance',
    walletCoins: 'Coins',
    walletTransactions: 'Transactions',
    totalBalance: 'Total Balance',
    addMoney: 'Add Money',
    noTransactions: 'No transactions yet',
    noTransactionsDesc: 'Your wallet history will appear here.',
    // ── Orders screen ──
    ordersTitle: 'My Trips',
    noTrips: 'No trips yet',
    noTripsDesc: 'Book your first ride or delivery and it will show up here.',
    noCategoriesMatch: 'No categories match',
    noCategoriesMatchDesc: 'Try resetting the service type filter.',
    // ── Offers screen ──
    offersTitle: 'Offers & Promos',
    offersSubtitle: 'Exclusive deals for you',
    enterPromoCode: 'Enter promo code',
    applyCode: 'Apply',
    // ── Saved Addresses ──
    savedAddressesTitle: 'Saved Addresses',
    savedAddressesHint: 'Save your home, work and frequent locations for faster booking',
    savedAddressesProTip: '💡 Saved addresses appear as quick-select options when booking a ride or delivery.',
    addAddress: 'Add Address',
    editAddress: 'Edit Address',
    deleteAddress: 'Delete',
    confirmDelete: 'Delete Address',
    confirmDeleteMsg: 'Are you sure you want to delete this address?',
    // ── Payment Methods ──
    paymentMethodsTitle: 'Payment Methods',
    addPaymentMethod: 'Add Payment Method',
    paymentSecurity: 'Your payment information is encrypted and secured. We never store full card numbers.',
    // ── Location ──
    setLocationManually: 'Set your location manually',
    locationOffMsg: "Location access is off, so we can't detect where you are. Enter your area to see nearby drivers and accurate fares.",
    locationOff: 'Location is off',
    // ── Generic ──
    back: 'Back',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    referEarn: 'Refer & Earn',
    referDesc: 'Invite friends and earn ₹100 for every successful referral!',
    referNote: '*Rewards are credited after your friend completes their first ride. Valid for new users only.',
    paymentProcessing: 'Processing Payment...',
    paymentProcessingNote: 'Do not press back or close the app. Your payment is being processed securely.',
    // ── Chip labels (truck/packers screens) ──
    chipFuelTolls: '💡 Fuel & tolls included',
    chipDoorstepLoading: '🚚 Doorstep loading',
    chipLiveTracking: '📍 Live tracking',
    chipHassleFree: '🏠 Hassle-free shifting',
    chipFullPacking: '📦 Full packing',
    chipInsuredMove: '🛡️ Insured move',
    // ── Tags ──
    tagLocalSameDay: 'Local · Same Day',
    tagCityToCity: 'City to City · Per KM',
    tagLocalFullPacking: 'Local · Full Packing Team',
    tagLightShifting: 'Light Shifting · Budget Friendly',
    tagCityToCityIntercity: 'City to City · Intercity Move',
    tagSameDay: 'Same Day · Local',
    tagCityToCityKg: 'City to City · Per KG',
    tagUnder2Hours: 'Under 2 Hours',
    // ── Auth screens ──
    loginHeading: "Let's get started",
    loginSubheading: 'Login with your mobile number',
    loginFieldLabel: 'Mobile Number',
    loginPlaceholder: '10-digit mobile number',
    loginSendOtp: 'Send OTP',
    loginTermsPrefix: 'By continuing you agree to our',
    loginTermsLink: 'Terms & Conditions',
    loginTermsAnd: 'and',
    loginPrivacyLink: 'Privacy Policy',
    loginSending: 'Sending OTP…',
    loginErrorTooMany: 'Too many attempts. Please wait a minute and try again.',
    loginErrorInvalid: 'Please enter a valid mobile number',
    otpHeading: 'Verify OTP',
    otpSub: 'Enter the 6-digit code sent to',
    otpVerify: 'Verify & Continue',
    otpResendIn: 'RESEND OTP IN {seconds} SECONDS',
    otpDidntReceive: "Didn't receive the OTP?",
    otpRetry: 'Retry',
    otpErrorNoInternet: 'No internet connection. Please check your network and try again.',
    otpErrorTimeout: 'Request timed out. Please try again.',
    otpErrorServer: 'Something went wrong on our end. Please try again in a moment.',
    otpErrorInvalidOtp: 'The OTP you entered is incorrect. Please check and try again.',
    personalHeading: 'Personal Details',
    personalSubheading: 'Complete your profile to continue',
    personalNameLabel: 'Full Name',
    personalNamePlaceholder: 'Enter your full name',
    personalDobLabel: 'Date of Birth',
    personalDobPlaceholder: 'DD/MM/YYYY',
    personalEmailLabel: 'Email Address',
    personalEmailPlaceholder: 'Enter your email',
    personalContinue: 'Continue',
  },

  kn: {
    // ── Profile screen ──
    myProfile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    manageAccount: 'ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    savedAddresses: 'ಉಳಿಸಿದ ವಿಳಾಸಗಳು',
    paymentMethods: 'ಪಾವತಿ ವಿಧಾನಗಳು',
    language: 'ಭಾಷೆ',
    theme: 'ಥೀಮ್',
    helpSupport: 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    termsConditions: 'ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳು',
    logOut: 'ಲಾಗ್ ಔಟ್',
    logOutConfirmTitle: 'ಲಾಗ್ ಔಟ್',
    logOutConfirmMsg: 'ನೀವು ಖಂಡಿತವಾಗಿಯೂ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
    cancel: 'ರದ್ದುಮಾಡಿ',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    done: 'ಮುಗಿದಿದೆ',
    switchToDarkTheme: 'ಡಾರ್ಕ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ',
    switchToLightTheme: 'ಲೈಟ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ',
    version: 'Vahan360 v1.0.0',
    // ── Home screen ──
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ 👋',
    hi: 'ಹಲೋ',
    locationLabel: 'ಕೋರಮಂಗಲ, ಬೆಂಗಳೂರು',
    heroLine1: 'ರೈಡ್ ಮತ್ತು ಡೆಲಿವರಿಗಳನ್ನು ಬುಕ್ ಮಾಡಿ',
    heroLine2: 'ಸೆಕೆಂಡುಗಳಲ್ಲಿ ⚡',
    trustFast: 'ವೇಗ',
    trustSafe: 'ಸುರಕ್ಷಿತ',
    trustRated: '4.9 ರೇಟಿಂಗ್',
    searchHint: 'ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು ಅಥವಾ ಕಳುಹಿಸಬೇಕು?',
    categoryRide: 'ರೈಡ್',
    categoryLogistics: 'ಲಾಜಿಸ್ಟಿಕ್ಸ್',
    categoryTruck: 'ಟ್ರಕ್',
    categoryPackersMovers: 'ಪ್ಯಾಕರ್ಸ್ & ಮೂವರ್ಸ್',
    categoryParcel: 'ಪಾರ್ಸೆಲ್',
    // ── Packers & Movers screen ──
    packersMoversTitle: 'ಪ್ಯಾಕರ್ಸ್ & ಮೂವರ್ಸ್',
    packersMoversSubtitle: 'ನಿಮ್ಮ ಶಿಫ್ಟಿಂಗ್ ಸೇವೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    shiftingMiniTruck: 'ಮಿನಿ ಟ್ರಕ್',
    shiftingMiniTruckDesc: 'ನಗರದೊಳಗೆ',
    shiftingWithinCity: 'ನಗರದೊಳಗೆ',
    shiftingWithinCityDesc: 'ಸ್ಥಳೀಯ ಮನೆ ಮತ್ತು ಕಚೇರಿ ಶಿಫ್ಟಿಂಗ್',
    shiftingBetweenCities: 'ನಗರಗಳ ನಡುವೆ',
    shiftingBetweenCitiesDesc: 'ಅಂತರ-ನಗರ ಸ್ಥಳಾಂತರ',
    // ── Truck screen ──
    truckTitle: 'ಟ್ರಕ್',
    truckSubtitle: 'ನಿಮ್ಮ ಸೇವೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    truckWithinCity: 'ನಗರದೊಳಗೆ',
    truckWithinCityDesc: 'ಸ್ಥಳೀಯ ಸರಕು ಸಾಗಣೆ',
    truckInterCities: 'ನಗರಗಳ ನಡುವೆ',
    truckInterCitiesDesc: 'ನಗರದಿಂದ ನಗರಕ್ಕೆ ಸಾಗಣೆ',
    truckLongTrips: 'ದೂರದ ಪ್ರಯಾಣ',
    truckLongTripsDesc: 'ದೂರದ ಸಾಗಣೆ',
    // ── Parcel screen ──
    parcelTitle: 'ಪಾರ್ಸೆಲ್',
    parcelSubtitle: 'ನಿಮ್ಮ ಡೆಲಿವರಿ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    parcelSameCity: 'ಅದೇ ನಗರ',
    parcelSameCityDesc: 'ಇಂದು ನಗರದೊಳಗೆ ಪಾರ್ಸೆಲ್ ತಲುಪಿಸಿ',
    parcelInterCity: 'ಅಂತರ ನಗರ',
    parcelInterCityDesc: 'ಮತ್ತೊಂದು ನಗರಕ್ಕೆ ಪಾರ್ಸೆಲ್ ಕಳುಹಿಸಿ',
    parcelExpress: 'ಎಕ್ಸ್‌ಪ್ರೆಸ್ ಡೆಲಿವರಿ',
    parcelExpressDesc: 'ಆದ್ಯತೆಯ ಅದೇ ದಿನದ ಡೆಲಿವರಿ',
    parcelFastDelivery: '📦 ವೇಗದ ಡೆಲಿವರಿ',
    parcelLiveTracking: '📍 ನೇರ ಟ್ರ್ಯಾಕಿಂಗ್',
    parcelSafeInsured: '🔒 ಸುರಕ್ಷಿತ & ವಿಮೆ',
    comingSoon: 'ಶೀಘ್ರದಲ್ಲೇ',
    // ── Vehicle screen ──
    chooseVehicle: 'ವಾಹನ ಆಯ್ಕೆ ಮಾಡಿ',
    confirmVehicle: 'ವಾಹನ ದೃಢಪಡಿಸಿ',
    // ── Tab bar ──
    tabHome: 'ಮನೆ',
    tabOrders: 'ಆದೇಶಗಳು',
    tabWallet: 'ವ್ಯಾಲೆಟ್',
    tabProfile: 'ಪ್ರೊಫೈಲ್',
    // ── Notifications screen ──
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    unreadCount: 'ಓದದ',
    allCaughtUp: 'ಎಲ್ಲವೂ ಓದಲಾಗಿದೆ!',
    markAllRead: 'ಎಲ್ಲ ಓದಿದಂತೆ ಗುರುತಿಸಿ',
    // ── Wallet screen ──
    vahanPay: 'Vahan Pay',
    walletSubtitle: 'ವೇಗದ & ಸುರಕ್ಷಿತ ವ್ಯಾಲೆಟ್ ಪಾವತಿಗಳು',
    walletBalance: 'ಬ್ಯಾಲೆನ್ಸ್',
    walletCoins: 'ನಾಣ್ಯಗಳು',
    walletTransactions: 'ವ್ಯವಹಾರಗಳು',
    totalBalance: 'ಒಟ್ಟು ಬ್ಯಾಲೆನ್ಸ್',
    addMoney: 'ಹಣ ಸೇರಿಸಿ',
    noTransactions: 'ಯಾವುದೇ ವ್ಯವಹಾರಗಳಿಲ್ಲ',
    noTransactionsDesc: 'ನಿಮ್ಮ ವ್ಯಾಲೆಟ್ ಇತಿಹಾಸ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
    // ── Orders screen ──
    ordersTitle: 'ನನ್ನ ಪ್ರಯಾಣಗಳು',
    noTrips: 'ಇನ್ನೂ ಯಾವುದೇ ಪ್ರಯಾಣಗಳಿಲ್ಲ',
    noTripsDesc: 'ನಿಮ್ಮ ಮೊದಲ ರೈಡ್ ಅಥವಾ ಡೆಲಿವರಿ ಬುಕ್ ಮಾಡಿ, ಅದು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
    noCategoriesMatch: 'ಯಾವ ವರ್ಗಗಳೂ ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    noCategoriesMatchDesc: 'ಸೇವಾ ಪ್ರಕಾರ ಫಿಲ್ಟರ್ ಮರುಹೊಂದಿಸಲು ಪ್ರಯತ್ನಿಸಿ.',
    // ── Offers screen ──
    offersTitle: 'ಆಫರ್‌ಗಳು & ಪ್ರೋಮೋಗಳು',
    offersSubtitle: 'ನಿಮಗಾಗಿ ವಿಶೇಷ ಡೀಲ್‌ಗಳು',
    enterPromoCode: 'ಪ್ರೋಮೋ ಕೋಡ್ ನಮೂದಿಸಿ',
    applyCode: 'ಅನ್ವಯಿಸಿ',
    // ── Saved Addresses ──
    savedAddressesTitle: 'ಉಳಿಸಿದ ವಿಳಾಸಗಳು',
    savedAddressesHint: 'ವೇಗದ ಬುಕಿಂಗ್‌ಗಾಗಿ ನಿಮ್ಮ ಮನೆ, ಕೆಲಸ ಮತ್ತು ಆಗಾಗ ಹೋಗುವ ಸ್ಥಳಗಳನ್ನು ಉಳಿಸಿ',
    savedAddressesProTip: '💡 ಉಳಿಸಿದ ವಿಳಾಸಗಳು ರೈಡ್ ಅಥವಾ ಡೆಲಿವರಿ ಬುಕ್ ಮಾಡುವಾಗ ತ್ವರಿತ ಆಯ್ಕೆ ಆಗಿ ಕಾಣಿಸುತ್ತವೆ.',
    addAddress: 'ವಿಳಾಸ ಸೇರಿಸಿ',
    editAddress: 'ವಿಳಾಸ ಸಂಪಾದಿಸಿ',
    deleteAddress: 'ಅಳಿಸಿ',
    confirmDelete: 'ವಿಳಾಸ ಅಳಿಸಿ',
    confirmDeleteMsg: 'ನೀವು ಖಂಡಿತವಾಗಿಯೂ ಈ ವಿಳಾಸವನ್ನು ಅಳಿಸಲು ಬಯಸುವಿರಾ?',
    // ── Payment Methods ──
    paymentMethodsTitle: 'ಪಾವತಿ ವಿಧಾನಗಳು',
    addPaymentMethod: 'ಪಾವತಿ ವಿಧಾನ ಸೇರಿಸಿ',
    paymentSecurity: 'ನಿಮ್ಮ ಪಾವತಿ ಮಾಹಿತಿ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮತ್ತು ಸುರಕ್ಷಿತವಾಗಿದೆ. ನಾವು ಎಂದಿಗೂ ಪೂರ್ಣ ಕಾರ್ಡ್ ಸಂಖ್ಯೆಗಳನ್ನು ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.',
    // ── Location ──
    setLocationManually: 'ಸ್ಥಳವನ್ನು ಕೈಯಾರೆ ಹೊಂದಿಸಿ',
    locationOffMsg: "ಸ್ಥಳ ಪ್ರವೇಶ ಆಫ್ ಆಗಿದೆ, ಹಾಗಾಗಿ ನೀವು ಎಲ್ಲಿದ್ದೀರಿ ಎಂದು ಪತ್ತೆ ಮಾಡಲು ಸಾಧ್ಯವಿಲ್ಲ.",
    locationOff: 'ಸ್ಥಳ ಆಫ್ ಆಗಿದೆ',
    // ── Generic ──
    back: 'ಹಿಂದೆ',
    confirm: 'ದೃಢಪಡಿಸಿ',
    save: 'ಉಳಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    edit: 'ಸಂಪಾದಿಸಿ',
    close: 'ಮುಚ್ಚಿ',
    referEarn: 'ರೆಫರ್ & ಗಳಿಸಿ',
    referDesc: 'ಸ್ನೇಹಿತರನ್ನು ಆಹ್ವಾನಿಸಿ ಮತ್ತು ಪ್ರತಿ ಯಶಸ್ವಿ ರೆಫರಲ್‌ಗೆ ₹100 ಗಳಿಸಿ!',
    referNote: '*ನಿಮ್ಮ ಸ್ನೇಹಿತರು ಮೊದಲ ರೈಡ್ ಪೂರ್ಣಗೊಳಿಸಿದ ನಂತರ ಪ್ರತಿಫಲ ಜಮೆಯಾಗುತ್ತದೆ. ಹೊಸ ಬಳಕೆದಾರರಿಗೆ ಮಾತ್ರ ಮಾನ್ಯ.',
    paymentProcessing: 'ಪಾವತಿ ಪ್ರಕ್ರಿಯೆ ನಡೆಯುತ್ತಿದೆ...',
    paymentProcessingNote: 'ಹಿಂದೆ ಒತ್ತಬೇಡಿ ಅಥವಾ ಅಪ್ಲಿಕೇಶನ್ ಮುಚ್ಚಬೇಡಿ. ನಿಮ್ಮ ಪಾವತಿ ಸುರಕ್ಷಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆ ನಡೆಯುತ್ತಿದೆ.',
    // ── Chip labels ──
    chipFuelTolls: '💡 ಇಂಧನ & ಟೋಲ್ ಸೇರಿದೆ',
    chipDoorstepLoading: '🚚 ಬಾಗಿಲ ಲೋಡಿಂಗ್',
    chipLiveTracking: '📍 ನೇರ ಟ್ರ್ಯಾಕಿಂಗ್',
    chipHassleFree: '🏠 ಸಮಸ್ಯಾರಹಿತ ಶಿಫ್ಟಿಂಗ್',
    chipFullPacking: '📦 ಪೂರ್ಣ ಪ್ಯಾಕಿಂಗ್',
    chipInsuredMove: '🛡️ ವಿಮೆ ಇರುವ ಸ್ಥಳಾಂತರ',
    // ── Tags ──
    tagLocalSameDay: 'ಸ್ಥಳೀಯ · ಅದೇ ದಿನ',
    tagCityToCity: 'ನಗರದಿಂದ ನಗರಕ್ಕೆ · ಕಿಮೀ ಪ್ರತಿ',
    tagLocalFullPacking: 'ಸ್ಥಳೀಯ · ಪೂರ್ಣ ಪ್ಯಾಕಿಂಗ್ ತಂಡ',
    tagLightShifting: 'ಹಗುರ ಶಿಫ್ಟಿಂಗ್ · ಕಡಿಮೆ ದರ',
    tagCityToCityIntercity: 'ನಗರದಿಂದ ನಗರಕ್ಕೆ · ಅಂತರ ನಗರ',
    tagSameDay: 'ಅದೇ ದಿನ · ಸ್ಥಳೀಯ',
    tagCityToCityKg: 'ನಗರದಿಂದ ನಗರಕ್ಕೆ · ಕೆಜಿ ಪ್ರತಿ',
    tagUnder2Hours: '2 ಗಂಟೆಯೊಳಗೆ',
    // ── Auth screens ──
    loginHeading: 'ಪ್ರಾರಂಭಿಸೋಣ',
    loginSubheading: 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯಿಂದ ಲಾಗಿನ್ ಮಾಡಿ',
    loginFieldLabel: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    loginPlaceholder: '10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    loginSendOtp: 'OTP ಕಳುಹಿಸಿ',
    loginTermsPrefix: 'ಮುಂದುವರಿಯುವ ಮೂಲಕ ನೀವು ನಮ್ಮ',
    loginTermsLink: 'ನಿಯಮಗಳು & ಷರತ್ತುಗಳು',
    loginTermsAnd: 'ಮತ್ತು',
    loginPrivacyLink: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    loginSending: 'OTP ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…',
    loginErrorTooMany: 'ಹೆಚ್ಚು ಪ್ರಯತ್ನಗಳು. ಒಂದು ನಿಮಿಷ ಕಾಯಿರಿ.',
    loginErrorInvalid: 'ಮಾನ್ಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    otpHeading: 'OTP ಪರಿಶೀಲಿಸಿ',
    otpSub: '6 ಅಂಕಿ ಕೋಡ್ ಕಳುಹಿಸಲಾಗಿದೆ',
    otpVerify: 'ಪರಿಶೀಲಿಸಿ & ಮುಂದುವರಿಯಿರಿ',
    otpResendIn: '{seconds} ಸೆಕೆಂಡ್‌ಗಳಲ್ಲಿ OTP ಮರು-ಕಳುಹಿಸಿ',
    otpDidntReceive: 'OTP ಸಿಗಲಿಲ್ಲವೇ?',
    otpRetry: 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    otpErrorNoInternet: 'ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಇಲ್ಲ. ನಿಮ್ಮ ನೆಟ್‌ವರ್ಕ್ ಪರಿಶೀಲಿಸಿ.',
    otpErrorTimeout: 'ವಿನಂತಿ ಸಮಯ ಮೀರಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    otpErrorServer: 'ಏನೋ ತಪ್ಪಾಯಿತು. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಪ್ರಯತ್ನಿಸಿ.',
    otpErrorInvalidOtp: 'ನೀವು ನಮೂದಿಸಿದ OTP ತಪ್ಪಾಗಿದೆ. ಪರಿಶೀಲಿಸಿ.',
    personalHeading: 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
    personalSubheading: 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
    personalNameLabel: 'ಪೂರ್ಣ ಹೆಸರು',
    personalNamePlaceholder: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
    personalDobLabel: 'ಜನ್ಮ ದಿನಾಂಕ',
    personalDobPlaceholder: 'DD/MM/YYYY',
    personalEmailLabel: 'ಇಮೇಲ್ ವಿಳಾಸ',
    personalEmailPlaceholder: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ',
    personalContinue: 'ಮುಂದುವರಿಯಿರಿ',
  },

  ta: {
    // ── Profile screen ──
    myProfile: 'என் சுயவிவரம்',
    manageAccount: 'உங்கள் கணக்கு மற்றும் விருப்பங்களை நிர்வகிக்கவும்',
    savedAddresses: 'சேமிக்கப்பட்ட முகவரிகள்',
    paymentMethods: 'கட்டண முறைகள்',
    language: 'மொழி',
    theme: 'தீம்',
    helpSupport: 'உதவி மற்றும் ஆதரவு',
    termsConditions: 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
    logOut: 'வெளியேறு',
    logOutConfirmTitle: 'வெளியேறு',
    logOutConfirmMsg: 'நீங்கள் நிச்சயமாக வெளியேற விரும்புகிறீர்களா?',
    cancel: 'ரத்து செய்',
    selectLanguage: 'மொழியை தேர்ந்தெடுக்கவும்',
    done: 'முடிந்தது',
    switchToDarkTheme: 'டார்க் தீமுக்கு மாறவும்',
    switchToLightTheme: 'லைட் தீமுக்கு மாறவும்',
    version: 'Vahan360 v1.0.0',
    // ── Home screen ──
    welcomeBack: 'மீண்டும் வரவேற்கிறோம் 👋',
    hi: 'வணக்கம்',
    locationLabel: 'கோரமங்களா, பெங்களூரு',
    heroLine1: 'ரைடுகள் மற்றும் டெலிவரிகளை',
    heroLine2: 'நொடிகளில் முன்பதிவு செய்யுங்கள் ⚡',
    trustFast: 'வேகம்',
    trustSafe: 'பாதுகாப்பு',
    trustRated: '4.9 மதிப்பீடு',
    searchHint: 'எங்கு செல்ல அல்லது அனுப்ப வேண்டும்?',
    categoryRide: 'ரைடு',
    categoryLogistics: 'லாஜிஸ்டிக்ஸ்',
    categoryTruck: 'லாரி',
    categoryPackersMovers: 'பேக்கர்ஸ் & மூவர்ஸ்',
    categoryParcel: 'பார்சல்',
    // ── Packers & Movers screen ──
    packersMoversTitle: 'பேக்கர்ஸ் & மூவர்ஸ்',
    packersMoversSubtitle: 'உங்கள் இடமாற்று சேவையைத் தேர்ந்தெடுக்கவும்',
    shiftingMiniTruck: 'மினி லாரி',
    shiftingMiniTruckDesc: 'நகருக்குள்',
    shiftingWithinCity: 'நகருக்குள்',
    shiftingWithinCityDesc: 'உள்ளூர் வீடு மற்றும் அலுவலக இடமாற்றம்',
    shiftingBetweenCities: 'நகரங்களுக்கு இடையில்',
    shiftingBetweenCitiesDesc: 'நகரம் இடையேயான இடமாற்றம்',
    // ── Truck screen ──
    truckTitle: 'லாரி',
    truckSubtitle: 'உங்கள் சேவையைத் தேர்ந்தெடுக்கவும்',
    truckWithinCity: 'நகருக்குள்',
    truckWithinCityDesc: 'உள்ளூர் சரக்கு போக்குவரத்து',
    truckInterCities: 'நகரங்களுக்கு இடையில்',
    truckInterCitiesDesc: 'நகரம் முதல் நகரம் போக்குவரத்து',
    truckLongTrips: 'நீண்ட பயணங்கள்',
    truckLongTripsDesc: 'நீண்ட தூர போக்குவரத்து',
    // ── Parcel screen ──
    parcelTitle: 'பார்சல்',
    parcelSubtitle: 'உங்கள் டெலிவரி வகையைத் தேர்ந்தெடுக்கவும்',
    parcelSameCity: 'அதே நகரம்',
    parcelSameCityDesc: 'இன்று நகரத்திற்குள் பார்சல் அனுப்பவும்',
    parcelInterCity: 'இடை நகர',
    parcelInterCityDesc: 'மற்றொரு நகரத்திற்கு பார்சல் அனுப்பவும்',
    parcelExpress: 'எக்ஸ்பிரஸ் டெலிவரி',
    parcelExpressDesc: 'முன்னுரிமை அதே நாள் டெலிவரி',
    parcelFastDelivery: '📦 வேக டெலிவரி',
    parcelLiveTracking: '📍 நேரடி கண்காணிப்பு',
    parcelSafeInsured: '🔒 பாதுகாப்பு & காப்பீடு',
    comingSoon: 'விரைவில் வருகிறது',
    // ── Vehicle screen ──
    chooseVehicle: 'வாகனம் தேர்ந்தெடுக்கவும்',
    confirmVehicle: 'வாகனம் உறுதிப்படுத்தவும்',
    // ── Tab bar ──
    tabHome: 'முகப்பு',
    tabOrders: 'ஆர்டர்கள்',
    tabWallet: 'வாலட்',
    tabProfile: 'சுயவிவரம்',
    // ── Notifications screen ──
    notifications: 'அறிவிப்புகள்',
    unreadCount: 'படிக்காத',
    allCaughtUp: 'எல்லாம் படிக்கப்பட்டது!',
    markAllRead: 'அனைத்தையும் படித்ததாக குறிக்கவும்',
    // ── Wallet screen ──
    vahanPay: 'Vahan Pay',
    walletSubtitle: 'வேக & பாதுகாப்பான வாலட் பணம்',
    walletBalance: 'இருப்பு',
    walletCoins: 'நாணயங்கள்',
    walletTransactions: 'பரிவர்த்தனைகள்',
    totalBalance: 'மொத்த இருப்பு',
    addMoney: 'பணம் சேர்க்கவும்',
    noTransactions: 'பரிவர்த்தனைகள் எதுவும் இல்லை',
    noTransactionsDesc: 'உங்கள் வாலட் வரலாறு இங்கே தோன்றும்.',
    // ── Orders screen ──
    ordersTitle: 'என் பயணங்கள்',
    noTrips: 'இன்னும் பயணங்கள் இல்லை',
    noTripsDesc: 'உங்கள் முதல் ரைடு அல்லது டெலிவரியை முன்பதிவு செய்யுங்கள், அது இங்கே தோன்றும்.',
    noCategoriesMatch: 'வகைகள் எதுவும் பொருந்தவில்லை',
    noCategoriesMatchDesc: 'சேவை வகை வடிகட்டியை மீட்டமைக்க முயற்சிக்கவும்.',
    // ── Offers screen ──
    offersTitle: 'சலுகைகள் & பரிசு குறியீடுகள்',
    offersSubtitle: 'உங்களுக்கான சிறப்பு டீல்கள்',
    enterPromoCode: 'பரிசு குறியீட்டை உள்ளிடவும்',
    applyCode: 'பயன்படுத்து',
    // ── Saved Addresses ──
    savedAddressesTitle: 'சேமிக்கப்பட்ட முகவரிகள்',
    savedAddressesHint: 'வேக முன்பதிவுக்கு உங்கள் வீடு, அலுவலகம் மற்றும் அடிக்கடி செல்லும் இடங்களை சேமிக்கவும்',
    savedAddressesProTip: '💡 சேமிக்கப்பட்ட முகவரிகள் ரைடு அல்லது டெலிவரி முன்பதிவு செய்யும்போது விரைவு விருப்பமாக தோன்றும்.',
    addAddress: 'முகவரி சேர்க்கவும்',
    editAddress: 'முகவரி திருத்தவும்',
    deleteAddress: 'நீக்கவும்',
    confirmDelete: 'முகவரியை நீக்கவும்',
    confirmDeleteMsg: 'இந்த முகவரியை நிச்சயமாக நீக்க விரும்புகிறீர்களா?',
    // ── Payment Methods ──
    paymentMethodsTitle: 'கட்டண முறைகள்',
    addPaymentMethod: 'கட்டண முறையை சேர்க்கவும்',
    paymentSecurity: 'உங்கள் கட்டண தகவல் குறியாக்கம் மற்றும் பாதுகாப்பாக உள்ளது. நாங்கள் ஒருபோதும் முழு அட்டை எண்களை சேமிப்பதில்லை.',
    // ── Location ──
    setLocationManually: 'இடத்தை கைமுறையாக அமைக்கவும்',
    locationOffMsg: 'இட அணுகல் அணைக்கப்பட்டுள்ளது, எனவே நீங்கள் எங்கிருக்கிறீர்கள் என்று கண்டறிய முடியாது.',
    locationOff: 'இடம் அணைக்கப்பட்டுள்ளது',
    // ── Generic ──
    back: 'பின்னால்',
    confirm: 'உறுதிப்படுத்தவும்',
    save: 'சேமிக்கவும்',
    delete: 'நீக்கவும்',
    edit: 'திருத்தவும்',
    close: 'மூடவும்',
    referEarn: 'பரிந்துரை & சம்பாதிக்கவும்',
    referDesc: 'நண்பர்களை அழைத்து ஒவ்வொரு வெற்றிகரமான பரிந்துரைக்கும் ₹100 சம்பாதிக்கவும்!',
    referNote: '*உங்கள் நண்பர் முதல் ரைடை முடித்த பிறகு வெகுமதிகள் வரவு வைக்கப்படும். புதிய பயனர்களுக்கு மட்டுமே.',
    paymentProcessing: 'கட்டணம் செயலாக்கப்படுகிறது...',
    paymentProcessingNote: 'பின்நோக்கி அழுத்தாதீர்கள் அல்லது பயன்பாட்டை மூடாதீர்கள். உங்கள் கட்டணம் பாதுகாப்பாக செயலாக்கப்படுகிறது.',
    // ── Chip labels ──
    chipFuelTolls: '💡 எரிபொருள் & சுங்கம் சேர்க்கப்பட்டுள்ளது',
    chipDoorstepLoading: '🚚 வாசல்படி ஏற்றுதல்',
    chipLiveTracking: '📍 நேரடி கண்காணிப்பு',
    chipHassleFree: '🏠 சிரமமற்ற இடமாற்றம்',
    chipFullPacking: '📦 முழு பேக்கிங்',
    chipInsuredMove: '🛡️ காப்பீடு செய்யப்பட்ட இடமாற்றம்',
    // ── Tags ──
    tagLocalSameDay: 'உள்ளூர் · அதே நாள்',
    tagCityToCity: 'நகரம் முதல் நகரம் · கி.மீ வாரியாக',
    tagLocalFullPacking: 'உள்ளூர் · முழு பேக்கிங் குழு',
    tagLightShifting: 'இலகு இடமாற்றம் · மலிவான விலை',
    tagCityToCityIntercity: 'நகரம் முதல் நகரம் · இடை நகர',
    tagSameDay: 'அதே நாள் · உள்ளூர்',
    tagCityToCityKg: 'நகரம் முதல் நகரம் · கிலோ வாரியாக',
    tagUnder2Hours: '2 மணி நேரத்திற்குள்',
    // ── Auth screens ──
    loginHeading: 'தொடங்குவோம்',
    loginSubheading: 'உங்கள் மொபைல் எண்ணால் உள்நுழைக',
    loginFieldLabel: 'மொபைல் எண்',
    loginPlaceholder: '10 இலக்க மொபைல் எண்',
    loginSendOtp: 'OTP அனுப்பு',
    loginTermsPrefix: 'தொடர்வதன் மூலம் நீங்கள் எங்கள்',
    loginTermsLink: 'விதிமுறைகள் & நிபந்தனைகள்',
    loginTermsAnd: 'மற்றும்',
    loginPrivacyLink: 'தனியுரிமைக் கொள்கை',
    loginSending: 'OTP அனுப்பப்படுகிறது…',
    loginErrorTooMany: 'மிகவும் அதிக முயற்சிகள். ஒரு நிமிடம் காத்திருங்கள்.',
    loginErrorInvalid: 'சரியான மொபைல் எண்ணை உள்ளிடவும்',
    otpHeading: 'OTP சரிபார்க்கவும்',
    otpSub: '6 இலக்க குறியீடு அனுப்பப்பட்டது',
    otpVerify: 'சரிபார்த்து தொடரவும்',
    otpResendIn: '{seconds} விநாடிகளில் OTP மீண்டும் அனுப்பு',
    otpDidntReceive: 'OTP கிடைக்கவில்லையா?',
    otpRetry: 'மீண்டும் முயற்சி',
    otpErrorNoInternet: 'இணைய இணைப்பு இல்லை. நெட்வொர்க்கை சரிபார்க்கவும்.',
    otpErrorTimeout: 'கோரிக்கை நேரம் முடிந்தது. மீண்டும் முயற்சிக்கவும்.',
    otpErrorServer: 'ஏதோ தவறானது. கொஞ்ச நேரம் கழித்து முயற்சிக்கவும்.',
    otpErrorInvalidOtp: 'உள்ளிட்ட OTP தவறானது. சரிபார்க்கவும்.',
    personalHeading: 'தனிப்பட்ட விவரங்கள்',
    personalSubheading: 'தொடர உங்கள் சுயவிவரத்தை நிறைவு செய்யுங்கள்',
    personalNameLabel: 'முழு பெயர்',
    personalNamePlaceholder: 'உங்கள் முழு பெயரை உள்ளிடவும்',
    personalDobLabel: 'பிறந்த தேதி',
    personalDobPlaceholder: 'DD/MM/YYYY',
    personalEmailLabel: 'மின்னஞ்சல் முகவரி',
    personalEmailPlaceholder: 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
    personalContinue: 'தொடர',
  },

  te: {
    // ── Profile screen ──
    myProfile: 'నా ప్రొఫైల్',
    manageAccount: 'మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి',
    savedAddresses: 'సేవ్ చేసిన చిరునామాలు',
    paymentMethods: 'చెల్లింపు పద్ధతులు',
    language: 'భాష',
    theme: 'థీమ్',
    helpSupport: 'సహాయం మరియు మద్దతు',
    termsConditions: 'నిబంధనలు మరియు షరతులు',
    logOut: 'లాగ్ అవుట్',
    logOutConfirmTitle: 'లాగ్ అవుట్',
    logOutConfirmMsg: 'మీరు నిజంగా లాగ్ అవుట్ చేయాలనుకుంటున్నారా?',
    cancel: 'రద్దు',
    selectLanguage: 'భాషను ఎంచుకోండి',
    done: 'పూర్తయింది',
    switchToDarkTheme: 'డార్క్ థీమ్‌కు మారండి',
    switchToLightTheme: 'లైట్ థీమ్‌కు మారండి',
    version: 'Vahan360 v1.0.0',
    // ── Home screen ──
    welcomeBack: 'తిరిగి స్వాగతం 👋',
    hi: 'హలో',
    locationLabel: 'కోరమంగళ, బెంగళూరు',
    heroLine1: 'రైడ్‌లు & డెలివరీలను',
    heroLine2: 'సెకన్లలో బుక్ చేయండి ⚡',
    trustFast: 'వేగవంతం',
    trustSafe: 'సురక్షితం',
    trustRated: '4.9 రేటింగ్',
    searchHint: 'ఎక్కడికి వెళ్లాలి లేదా పంపాలి?',
    categoryRide: 'రైడ్',
    categoryLogistics: 'లాజిస్టిక్స్',
    categoryTruck: 'ట్రక్',
    categoryPackersMovers: 'ప్యాకర్స్ & మూవర్స్',
    categoryParcel: 'పార్సెల్',
    // ── Packers & Movers screen ──
    packersMoversTitle: 'ప్యాకర్స్ & మూవర్స్',
    packersMoversSubtitle: 'మీ షిఫ్టింగ్ సేవను ఎంచుకోండి',
    shiftingMiniTruck: 'మినీ ట్రక్',
    shiftingMiniTruckDesc: 'నగరంలోనే',
    shiftingWithinCity: 'నగరంలోనే',
    shiftingWithinCityDesc: 'స్థానిక ఇల్లు మరియు ఆఫీసు షిఫ్టింగ్',
    shiftingBetweenCities: 'నగరాల మధ్య',
    shiftingBetweenCitiesDesc: 'ఇంటర్‌సిటీ రీలొకేషన్',
    // ── Truck screen ──
    truckTitle: 'ట్రక్',
    truckSubtitle: 'మీ సేవను ఎంచుకోండి',
    truckWithinCity: 'నగరంలోనే',
    truckWithinCityDesc: 'స్థానిక సరుకు రవాణా',
    truckInterCities: 'నగరాల మధ్య',
    truckInterCitiesDesc: 'నగరం నుండి నగరానికి రవాణా',
    truckLongTrips: 'లాంగ్ ట్రిప్స్',
    truckLongTripsDesc: 'దూర రవాణా',
    // ── Parcel screen ──
    parcelTitle: 'పార్సెల్',
    parcelSubtitle: 'మీ డెలివరీ రకాన్ని ఎంచుకోండి',
    parcelSameCity: 'అదే నగరం',
    parcelSameCityDesc: 'ఈరోజు నగరంలోనే పార్సెల్ డెలివరీ',
    parcelInterCity: 'ఇంటర్ సిటీ',
    parcelInterCityDesc: 'మరో నగరానికి పార్సెల్ పంపండి',
    parcelExpress: 'ఎక్స్‌ప్రెస్ డెలివరీ',
    parcelExpressDesc: 'ప్రాధాన్యత అదే రోజు డెలివరీ',
    parcelFastDelivery: '📦 వేగవంత డెలివరీ',
    parcelLiveTracking: '📍 లైవ్ ట్రాకింగ్',
    parcelSafeInsured: '🔒 సురక్షితం & భీమా',
    comingSoon: 'త్వరలో వస్తుంది',
    // ── Vehicle screen ──
    chooseVehicle: 'వాహనం ఎంచుకోండి',
    confirmVehicle: 'వాహనం నిర్ధారించండి',
    // ── Tab bar ──
    tabHome: 'హోమ్',
    tabOrders: 'ఆర్డర్లు',
    tabWallet: 'వాలెట్',
    tabProfile: 'ప్రొఫైల్',
    // ── Notifications screen ──
    notifications: 'నోటిఫికేషన్లు',
    unreadCount: 'చదవని',
    allCaughtUp: 'అన్నీ చదవబడ్డాయి!',
    markAllRead: 'అన్నీ చదివినట్లు గుర్తించండి',
    // ── Wallet screen ──
    vahanPay: 'Vahan Pay',
    walletSubtitle: 'వేగవంత & సురక్షిత వాలెట్ చెల్లింపులు',
    walletBalance: 'బ్యాలెన్స్',
    walletCoins: 'కాయిన్లు',
    walletTransactions: 'లావాదేవీలు',
    totalBalance: 'మొత్తం బ్యాలెన్స్',
    addMoney: 'డబ్బు జోడించండి',
    noTransactions: 'లావాదేవీలు ఏమీ లేవు',
    noTransactionsDesc: 'మీ వాలెట్ చరిత్ర ఇక్కడ కనిపిస్తుంది.',
    // ── Orders screen ──
    ordersTitle: 'నా ట్రిప్‌లు',
    noTrips: 'ఇంకా ట్రిప్‌లు లేవు',
    noTripsDesc: 'మీ మొదటి రైడ్ లేదా డెలివరీ బుక్ చేయండి, అది ఇక్కడ కనిపిస్తుంది.',
    noCategoriesMatch: 'ఏ వర్గాలూ సరిపోలలేదు',
    noCategoriesMatchDesc: 'సేవా రకం ఫిల్టర్ రీసెట్ చేయడానికి ప్రయత్నించండి.',
    // ── Offers screen ──
    offersTitle: 'ఆఫర్లు & ప్రోమోలు',
    offersSubtitle: 'మీ కోసం ప్రత్యేక డీల్స్',
    enterPromoCode: 'ప్రోమో కోడ్ నమోదు చేయండి',
    applyCode: 'వర్తింపజేయి',
    // ── Saved Addresses ──
    savedAddressesTitle: 'సేవ్ చేసిన చిరునామాలు',
    savedAddressesHint: 'వేగంగా బుకింగ్ కోసం మీ ఇల్లు, పని మరియు తరచుగా వెళ్ళే స్థలాలను సేవ్ చేయండి',
    savedAddressesProTip: '💡 సేవ్ చేసిన చిరునామాలు రైడ్ లేదా డెలివరీ బుకింగ్ చేసేటప్పుడు శీఘ్ర ఎంపికగా కనిపిస్తాయి.',
    addAddress: 'చిరునామా జోడించండి',
    editAddress: 'చిరునామా సవరించండి',
    deleteAddress: 'తొలగించు',
    confirmDelete: 'చిరునామా తొలగించు',
    confirmDeleteMsg: 'మీరు నిజంగా ఈ చిరునామాను తొలగించాలనుకుంటున్నారా?',
    // ── Payment Methods ──
    paymentMethodsTitle: 'చెల్లింపు పద్ధతులు',
    addPaymentMethod: 'చెల్లింపు పద్ధతి జోడించండి',
    paymentSecurity: 'మీ చెల్లింపు సమాచారం గుప్తీకరించబడి సురక్షితంగా ఉంది. మేము ఎప్పుడూ పూర్తి కార్డ్ నంబర్లు నిల్వ చేయము.',
    // ── Location ──
    setLocationManually: 'స్థానాన్ని మాన్యువల్‌గా సెట్ చేయండి',
    locationOffMsg: 'స్థాన యాక్సెస్ ఆఫ్ చేయబడింది, కాబట్టి మీరు ఎక్కడ ఉన్నారో గుర్తించలేము.',
    locationOff: 'స్థానం ఆఫ్ చేయబడింది',
    // ── Generic ──
    back: 'వెనకకు',
    confirm: 'నిర్ధారించండి',
    save: 'సేవ్ చేయండి',
    delete: 'తొలగించు',
    edit: 'సవరించు',
    close: 'మూసివేయి',
    referEarn: 'రిఫర్ & సంపాదించండి',
    referDesc: 'స్నేహితులను ఆహ్వానించండి మరియు ప్రతి విజయవంతమైన రిఫరల్‌కు ₹100 సంపాదించండి!',
    referNote: '*మీ స్నేహితుడు మొదటి రైడ్ పూర్తి చేసిన తర్వాత రివార్డులు క్రెడిట్ చేయబడతాయి. కొత్త వినియోగదారులకు మాత్రమే చెల్లుతుంది.',
    paymentProcessing: 'చెల్లింపు ప్రాసెస్ అవుతోంది...',
    paymentProcessingNote: 'వెనకకు నొక్కవద్దు లేదా యాప్‌ను మూసివేయవద్దు. మీ చెల్లింపు సురక్షితంగా ప్రాసెస్ అవుతోంది.',
    // ── Chip labels ──
    chipFuelTolls: '💡 ఇంధనం & టోల్ చేర్చబడింది',
    chipDoorstepLoading: '🚚 వాకిలి వద్ద లోడింగ్',
    chipLiveTracking: '📍 లైవ్ ట్రాకింగ్',
    chipHassleFree: '🏠 ఇబ్బంది లేని షిఫ్టింగ్',
    chipFullPacking: '📦 పూర్తి ప్యాకింగ్',
    chipInsuredMove: '🛡️ బీమా కలిగిన తరలింపు',
    // ── Tags ──
    tagLocalSameDay: 'స్థానిక · అదే రోజు',
    tagCityToCity: 'నగరం నుండి నగరం · కి.మీ వారీగా',
    tagLocalFullPacking: 'స్థానిక · పూర్తి ప్యాకింగ్ బృందం',
    tagLightShifting: 'తేలికపాటి షిఫ్టింగ్ · తక్కువ ధర',
    tagCityToCityIntercity: 'నగరం నుండి నగరం · ఇంటర్‌సిటీ',
    tagSameDay: 'అదే రోజు · స్థానిక',
    tagCityToCityKg: 'నగరం నుండి నగరం · కిలో వారీగా',
    tagUnder2Hours: '2 గంటలలోపు',
    // ── Auth screens ──
    loginHeading: 'ప్రారంభిద్దాం',
    loginSubheading: 'మీ మొబైల్ నంబర్‌తో లాగిన్ చేయండి',
    loginFieldLabel: 'మొబైల్ నంబర్',
    loginPlaceholder: '10 అంకెల మొబైల్ నంబర్',
    loginSendOtp: 'OTP పంపండి',
    loginTermsPrefix: 'కొనసాగించడం ద్వారా మీరు మా',
    loginTermsLink: 'నిబంధనలు & షరతులు',
    loginTermsAnd: 'మరియు',
    loginPrivacyLink: 'గోప్యతా విధానం',
    loginSending: 'OTP పంపబడుతోంది…',
    loginErrorTooMany: 'చాలా ప్రయత్నాలు. దయచేసి ఒక నిమిషం వేచి ఉండండి.',
    loginErrorInvalid: 'దయచేసి చెల్లుబాటు అయ్యే మొబైల్ నంబర్ నమోదు చేయండి',
    otpHeading: 'OTP ధృవీకరించండి',
    otpSub: '6 అంకెల కోడ్ పంపబడింది',
    otpVerify: 'ధృవీకరించి కొనసాగండి',
    otpResendIn: '{seconds} సెకన్లలో OTP మళ్ళీ పంపండి',
    otpDidntReceive: 'OTP రాలేదా?',
    otpRetry: 'మళ్ళీ ప్రయత్నించు',
    otpErrorNoInternet: 'ఇంటర్నెట్ కనెక్షన్ లేదు. నెట్‌వర్క్ తనిఖీ చేయండి.',
    otpErrorTimeout: 'అభ్యర్థన గడువు ముగిసింది. మళ్ళీ ప్రయత్నించండి.',
    otpErrorServer: 'ఏదో తప్పు జరిగింది. కొంత సమయం తర్వాత ప్రయత్నించండి.',
    otpErrorInvalidOtp: 'మీరు నమోదు చేసిన OTP తప్పు. తనిఖీ చేయండి.',
    personalHeading: 'వ్యక్తిగత వివరాలు',
    personalSubheading: 'కొనసాగించడానికి మీ ప్రొఫైల్ పూర్తి చేయండి',
    personalNameLabel: 'పూర్తి పేరు',
    personalNamePlaceholder: 'మీ పూర్తి పేరు నమోదు చేయండి',
    personalDobLabel: 'పుట్టిన తేదీ',
    personalDobPlaceholder: 'DD/MM/YYYY',
    personalEmailLabel: 'ఇమెయిల్ చిరునామా',
    personalEmailPlaceholder: 'మీ ఇమెయిల్ నమోదు చేయండి',
    personalContinue: 'కొనసాగించు',
  },

  hi: {
    // ── Profile screen ──
    myProfile: 'मेरी प्रोफ़ाइल',
    manageAccount: 'अपना खाता और प्राथमिकताएं प्रबंधित करें',
    savedAddresses: 'सहेजे गए पते',
    paymentMethods: 'भुगतान के तरीके',
    language: 'भाषा',
    theme: 'थीम',
    helpSupport: 'सहायता और समर्थन',
    termsConditions: 'नियम और शर्तें',
    logOut: 'लॉग आउट',
    logOutConfirmTitle: 'लॉग आउट',
    logOutConfirmMsg: 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    cancel: 'रद्द करें',
    selectLanguage: 'भाषा चुनें',
    done: 'हो गया',
    switchToDarkTheme: 'डार्क थीम पर बदलें',
    switchToLightTheme: 'लाइट थीम पर बदलें',
    version: 'Vahan360 v1.0.0',
    // ── Home screen ──
    welcomeBack: 'वापसी पर स्वागत है 👋',
    hi: 'नमस्ते',
    locationLabel: 'कोरमंगला, बेंगलुरु',
    heroLine1: 'राइड और डिलीवरी बुक करें',
    heroLine2: 'सेकंडों में ⚡',
    trustFast: 'तेज़',
    trustSafe: 'सुरक्षित',
    trustRated: '4.9 रेटेड',
    searchHint: 'कहाँ जाना है या भेजना है?',
    categoryRide: 'राइड',
    categoryLogistics: 'लॉजिस्टिक्स',
    categoryTruck: 'ट्रक',
    categoryPackersMovers: 'पैकर्स एंड मूवर्स',
    categoryParcel: 'पार्सल',
    // ── Packers & Movers screen ──
    packersMoversTitle: 'पैकर्स एंड मूवर्स',
    packersMoversSubtitle: 'अपनी शिफ्टिंग सेवा चुनें',
    shiftingMiniTruck: 'मिनी ट्रक',
    shiftingMiniTruckDesc: 'शहर के भीतर',
    shiftingWithinCity: 'शहर के भीतर',
    shiftingWithinCityDesc: 'स्थानीय घर और कार्यालय शिफ्टिंग',
    shiftingBetweenCities: 'शहरों के बीच',
    shiftingBetweenCitiesDesc: 'अंतरशहर स्थानांतरण',
    // ── Truck screen ──
    truckTitle: 'ट्रक',
    truckSubtitle: 'अपनी सेवा चुनें',
    truckWithinCity: 'शहर के भीतर',
    truckWithinCityDesc: 'स्थानीय माल परिवहन',
    truckInterCities: 'शहरों के बीच',
    truckInterCitiesDesc: 'शहर से शहर परिवहन',
    truckLongTrips: 'लंबी यात्रा',
    truckLongTripsDesc: 'लंबी दूरी का परिवहन',
    // ── Parcel screen ──
    parcelTitle: 'पार्सल',
    parcelSubtitle: 'अपनी डिलीवरी का प्रकार चुनें',
    parcelSameCity: 'एक ही शहर',
    parcelSameCityDesc: 'आज शहर के भीतर पार्सल डिलीवर करें',
    parcelInterCity: 'अंतरशहर',
    parcelInterCityDesc: 'दूसरे शहर में पार्सल भेजें',
    parcelExpress: 'एक्सप्रेस डिलीवरी',
    parcelExpressDesc: 'प्राथमिकता वाली उसी दिन डिलीवरी',
    parcelFastDelivery: '📦 तेज़ डिलीवरी',
    parcelLiveTracking: '📍 लाइव ट्रैकिंग',
    parcelSafeInsured: '🔒 सुरक्षित & बीमाकृत',
    comingSoon: 'जल्द आ रहा है',
    // ── Vehicle screen ──
    chooseVehicle: 'वाहन चुनें',
    confirmVehicle: 'वाहन पुष्टि करें',
    // ── Tab bar ──
    tabHome: 'होम',
    tabOrders: 'ऑर्डर',
    tabWallet: 'वॉलेट',
    tabProfile: 'प्रोफ़ाइल',
    // ── Notifications screen ──
    notifications: 'सूचनाएं',
    unreadCount: 'अपठित',
    allCaughtUp: 'सब पढ़ लिया!',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    // ── Wallet screen ──
    vahanPay: 'Vahan Pay',
    walletSubtitle: 'तेज़ और सुरक्षित वॉलेट भुगतान',
    walletBalance: 'बैलेंस',
    walletCoins: 'सिक्के',
    walletTransactions: 'लेनदेन',
    totalBalance: 'कुल बैलेंस',
    addMoney: 'पैसे जोड़ें',
    noTransactions: 'अभी कोई लेनदेन नहीं',
    noTransactionsDesc: 'आपका वॉलेट इतिहास यहाँ दिखेगा।',
    // ── Orders screen ──
    ordersTitle: 'मेरी यात्राएं',
    noTrips: 'अभी कोई यात्रा नहीं',
    noTripsDesc: 'अपनी पहली राइड या डिलीवरी बुक करें और यह यहाँ दिखेगी।',
    noCategoriesMatch: 'कोई श्रेणी मेल नहीं खाती',
    noCategoriesMatchDesc: 'सेवा प्रकार फ़िल्टर रीसेट करने का प्रयास करें।',
    // ── Offers screen ──
    offersTitle: 'ऑफर और प्रोमो',
    offersSubtitle: 'आपके लिए विशेष डील्स',
    enterPromoCode: 'प्रोमो कोड दर्ज करें',
    applyCode: 'लागू करें',
    // ── Saved Addresses ──
    savedAddressesTitle: 'सहेजे गए पते',
    savedAddressesHint: 'तेज़ बुकिंग के लिए अपना घर, काम और बार-बार जाने वाले स्थान सहेजें',
    savedAddressesProTip: '💡 सहेजे गए पते राइड या डिलीवरी बुक करते समय त्वरित विकल्प के रूप में दिखाई देते हैं।',
    addAddress: 'पता जोड़ें',
    editAddress: 'पता संपादित करें',
    deleteAddress: 'हटाएं',
    confirmDelete: 'पता हटाएं',
    confirmDeleteMsg: 'क्या आप वाकई इस पते को हटाना चाहते हैं?',
    // ── Payment Methods ──
    paymentMethodsTitle: 'भुगतान के तरीके',
    addPaymentMethod: 'भुगतान विधि जोड़ें',
    paymentSecurity: 'आपकी भुगतान जानकारी एन्क्रिप्टेड और सुरक्षित है। हम कभी भी पूरे कार्ड नंबर संग्रहीत नहीं करते।',
    // ── Location ──
    setLocationManually: 'स्थान मैन्युअल रूप से सेट करें',
    locationOffMsg: 'स्थान एक्सेस बंद है, इसलिए हम पता नहीं लगा सकते कि आप कहाँ हैं।',
    locationOff: 'स्थान बंद है',
    // ── Generic ──
    back: 'वापस',
    confirm: 'पुष्टि करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    close: 'बंद करें',
    referEarn: 'रेफर करें & कमाएं',
    referDesc: 'दोस्तों को आमंत्रित करें और हर सफल रेफरल पर ₹100 कमाएं!',
    referNote: '*आपके मित्र की पहली राइड पूरी होने के बाद पुरस्कार क्रेडिट किए जाते हैं। केवल नए उपयोगकर्ताओं के लिए वैध।',
    paymentProcessing: 'भुगतान प्रक्रिया जारी है...',
    paymentProcessingNote: 'वापस न दबाएं और ऐप बंद न करें। आपका भुगतान सुरक्षित रूप से प्रोसेस हो रहा है।',
    // ── Chip labels ──
    chipFuelTolls: '💡 ईंधन & टोल शामिल',
    chipDoorstepLoading: '🚚 दरवाज़े पर लोडिंग',
    chipLiveTracking: '📍 लाइव ट्रैकिंग',
    chipHassleFree: '🏠 परेशानी मुक्त शिफ्टिंग',
    chipFullPacking: '📦 पूर्ण पैकिंग',
    chipInsuredMove: '🛡️ बीमाकृत स्थानांतरण',
    // ── Tags ──
    tagLocalSameDay: 'स्थानीय · उसी दिन',
    tagCityToCity: 'शहर से शहर · प्रति किमी',
    tagLocalFullPacking: 'स्थानीय · पूर्ण पैकिंग टीम',
    tagLightShifting: 'हल्की शिफ्टिंग · किफायती',
    tagCityToCityIntercity: 'शहर से शहर · अंतरशहर',
    tagSameDay: 'उसी दिन · स्थानीय',
    tagCityToCityKg: 'शहर से शहर · प्रति किलो',
    tagUnder2Hours: '2 घंटे के अंदर',
    // ── Auth screens ──
    loginHeading: 'शुरू करते हैं',
    loginSubheading: 'अपने मोबाइल नंबर से लॉगिन करें',
    loginFieldLabel: 'मोबाइल नंबर',
    loginPlaceholder: '10 अंकों का मोबाइल नंबर',
    loginSendOtp: 'OTP भेजें',
    loginTermsPrefix: 'जारी रखने पर आप हमारी',
    loginTermsLink: 'नियम और शर्तें',
    loginTermsAnd: 'और',
    loginPrivacyLink: 'गोपनीयता नीति',
    loginSending: 'OTP भेजा जा रहा है…',
    loginErrorTooMany: 'बहुत अधिक प्रयास। कृपया एक मिनट प्रतीक्षा करें।',
    loginErrorInvalid: 'कृपया एक वैध मोबाइल नंबर दर्ज करें',
    otpHeading: 'OTP सत्यापित करें',
    otpSub: '6 अंकों का कोड भेजा गया',
    otpVerify: 'सत्यापित करें और जारी रखें',
    otpResendIn: '{seconds} सेकंड में OTP दोबारा भेजें',
    otpDidntReceive: 'OTP नहीं मिला?',
    otpRetry: 'पुनः प्रयास',
    otpErrorNoInternet: 'इंटरनेट कनेक्शन नहीं है। अपना नेटवर्क जांचें।',
    otpErrorTimeout: 'अनुरोध समय समाप्त। पुनः प्रयास करें।',
    otpErrorServer: 'कुछ गलत हो गया। थोड़ी देर बाद प्रयास करें।',
    otpErrorInvalidOtp: 'दर्ज किया गया OTP गलत है। कृपया जांचें।',
    personalHeading: 'व्यक्तिगत विवरण',
    personalSubheading: 'जारी रखने के लिए अपनी प्रोफ़ाइल पूरी करें',
    personalNameLabel: 'पूरा नाम',
    personalNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
    personalDobLabel: 'जन्म तिथि',
    personalDobPlaceholder: 'DD/MM/YYYY',
    personalEmailLabel: 'ईमेल पता',
    personalEmailPlaceholder: 'अपना ईमेल दर्ज करें',
    personalContinue: 'जारी रखें',
  },
} as const;

export type LangCode = keyof typeof TRANSLATIONS;
export type TranslationKey = keyof typeof TRANSLATIONS.en;

export const LANG_LIST: { code: LangCode; label: string; englishLabel: string }[] = [
  { code: 'en', label: 'English',  englishLabel: 'English'  },
  { code: 'kn', label: 'ಕನ್ನಡ',    englishLabel: 'Kannada'  },
  { code: 'ta', label: 'தமிழ்',    englishLabel: 'Tamil'    },
  { code: 'te', label: 'తెలుగు',   englishLabel: 'Telugu'   },
  { code: 'hi', label: 'हिंदी',    englishLabel: 'Hindi'    },
];

const LANG_STORAGE_KEY = '@vahan360_language';

// ---------------------------------------------------------------------------
// Context
// ---------------------------------------------------------------------------
interface LanguageContextType {
  lang: LangCode;
  setLang: (code: LangCode) => void;
  t: (key: TranslationKey) => string;
  /** false on first-ever launch (no language saved yet) — used by splash */
  hasChosen: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key) => TRANSLATIONS.en[key],
  hasChosen: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<LangCode>('en');
  const [loaded, setLoaded] = useState(false);
  const [hasChosen, setHasChosen] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANG_STORAGE_KEY).then((saved) => {
      if (saved && saved in TRANSLATIONS) {
        setLangState(saved as LangCode);
        setHasChosen(true);
      }
      setLoaded(true);
    });
  }, []);

  const setLang = (code: LangCode) => {
    setLangState(code);
    setHasChosen(true);
    AsyncStorage.setItem(LANG_STORAGE_KEY, code);
  };

  const t = (key: TranslationKey): string =>
    (TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS.en[key]) as string;

  if (!loaded) return null;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, hasChosen }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);