name: Cloud CI/CD Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  validate-and-deploy:
    runs-on: self-hosted  # This tells it to pick your active EC2 runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Deploy to Server Directory
        run: |
          sudo cp -R ${{ github.workspace }}/. /home/ubuntu/demo-page/
          
      - name: Restart Web Server
        run: sudo systemctl restart nginx